namespace Thandizo.DataModels.Ussd
{
    public class LanguageDTO
    {
        public string InitialWelcomeMessage { get; set; }
        public string CovidMenu { get; set; }
        public string WhatIsCovid { get; set; }
        public string ReturnToMainMenu { get; set; }
        public string ErrorMessage { get; set; }
        public string CovidSymptoms { get; set; }
        public string CovidPreventation { get; set; }
        public string CovidTreatment { get; set; }
        public string CovidInDanger { get; set; }
        public string CountryStatus { get; set; }
        public string SessionTimedOut { get; set; }
        public string TestingCompleted { get; set; }
        public string WelcomeBackMessage { get; set; }
        public string UserRegistrationFirstName { get; set; }
        public string CongratsMessage { get; set; }
        public string PleaseWait { get; set; }
        public string NotRegisteredPatient { get; set; }
        public string PatientStatusSubmit { get; set; }
        public string PatientStatusSelectedSymptoms { get; set; }
        public string PatientStatusSubmissionSuccess { get; set; }
        public string PatientStatusSubmissionRetry { get; set; }
        public string RetryAction { get; set; }
        public string SignOutMessage { get; set; }
        public string AlreadyRegisteredPatient { get; set; }
        public string PatientRegistrationDisclaimer { get; set; }
        public string PatientRegistrationFullName { get; set; }
        public string PatientRegistrationGender { get; set; }
        public string PatientRegistrationDOB { get; set; }
        public string PatientRegistrationPhysicalAddress { get; set; }
        public string PatientRegistrationHomeAddress { get; set; }
        public string PatientRegistrationDistrict { get; set; }
        public string PatientRegistrationNationality { get; set; }
        public string PatientRegistrationIdType { get; set; }
        public string PatientRegistrationIdNumber { get; set; }
        public string PatientRegistrationSummary { get; set; }
        public string ProceedConfirmation { get; set; }
        public string MultipleNationalities { get; set; }
        public string MultipleDistricts { get; set; }
        public string PatientRegistrationSuccess { get; set; }
        public string ResubmitPatientRegistration { get; set; }
        public string ConfirmPatientRegistrationStatus { get; set; }
        public string WorldStats { get; set; }

        public string ShareThisService { get; set; }
        public string Deaths { get; set; }
        public string Suspected { get; set; }
        public string Confirmed { get; set; }
        public string Recovered { get; set; }
        public string ActiveCases { get; set; }
        public string ReceivedSamples { get; set; }
        public string TestedSamples { get; set; }
        public string ErrorCountryStats { get; set; }
        public string ErrorPatientRecordRetrieval { get; set; }
        public string ErrorOptionsSeletion { get; set; }
        public string ErrorSymptomsRetrieval { get; set; }
        public string ErrorPatientRegistrationSubmission { get; set; }
        public string ErrorPatientStatusSubmission { get; set; }
        public string ErrorDistrictRetrieval { get; set; }
        public string ErrorDateFormat { get; set; }
        public string ErrorBlankDOB { get; set; }
        public string ErrorBlankHomeAddress { get; set; }
        public string ErrorBlankIdNumber { get; set; }
        public string ErrorOptionSeletion { get; set; }
        public string ErrorNationalityRetrieval { get; set; }
        public string ErrorBlankFullName { get; set; }
        public string ErrorGenderSelection { get; set; }
        public string Male { get; set; }
        public string Female { get; set; }
        public string ErrorBlankPhysicalAddress { get; set; }
        public string ErrorOnlyMalawians { get; set; }
        public string ForeignersInfo { get; set; }
        public string MainMenu { get; set; }
        public string CovidGetHelp { get; set; }
        public string NotFoundNationalStats { get; set; }
        public string NotFoundSymptoms { get; set; }
        public string NotFoundWorldStats { get; set; }
        public string TotalCases { get; set; }
        public string TotalRecovered { get; set; }
        public string TotalDeaths { get; set; }
        public string TotalNewCasesToday { get; set; }
        public string TotalNewDeathsToday { get; set; }
        public string TotalNewRecoveredToday { get; set; }
        public string ErrorBlankDistrict { get; set; }
        public string NotMatchedDistrictFound { get; set; }
        public string ErrorMinCharsIdNumber { get; set; }
        public string ErrorBlankNationality { get; set; }
        public string NoMatchingNationalityFound { get; set; }
        public string ErrorFirstLastNamesMissing { get; set; }
        public string ErrorMinCharsFirstName { get; set; }
        public string ErrorMinCharsSurname { get; set; }
        public string ErrorBlankGender { get; set; }
        public string ApplicationError { get; set; }
        public string ErrorInvalidSurname { get; set; }
        public string ErrorInvalidFirstName { get; set; }
        public string ErrorInvalidOtherNames { get; set; }
        public string ErrorMaxCharsFirstName { get; set; }
        public string ErrorMaxCharsSurname { get; set; }
        public string ErrorMaxCharsOtherNames { get; set; }
        public string ErrorMaxCharsHomeAddress { get; set; }
        public string ErrorMaxCharsPhysicalAddress { get; set; }
        public string HomeCountry { get; set; }
        public string IsSelfRegistration { get; set; }
        public string NextOfKinFullName { get; set; }
        public string NextOfKinPhoneNumber { get; set; }
        public string PatientSelection { get; set; }
        public string ErrorBlankNextOfKinFullName { get; set; }
        public string MultiplePatients { get; set; }
        public string ErrorBlankPhoneNumber { get; set; }
        public string InvalidPhoneNumber { get; set; }
        public string NotAllowedMobileOperator { get; set; }
        public string InvalidPhoneLength { get; set; }
        public string PhoneNumberExample { get; set; }
        public string Or { get; set; }
        public string ErrorCountryRetrieval { get; set; }
        public string ErrorBlankCountry { get; set; }
        public string NoMatchingCountryFound { get; set; }
        public string MultipleCountries { get; set; }
        public string NationalID { get; set; }
        public string Passport { get; set; }
        public string Cough { get; set; }
        public string Fever { get; set; }
        public string NoSymptoms { get; set; }
        public string RecordedBodyTemperature { get; set; }
        public string ShortnessOfBreath { get; set; }
        public string DriversLicense { get; set; }
        public string NotFoundIdentificationTypes { get; set; }
        public string StatisticsMenu { get; set; }
        public string PatientReportingMenu { get; set; }
        public string ReturnToPreviousMenu { get; set; }
        public string Next { get; set; }
        public string GetAccessTokenFailed { get; set; }
    }
}
